version: '3'
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "9000:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    mysql:
        image: "mariadb:10.5"
        volumes:
            - ${PWD:-./}/mysql:/var/data/db/mysql/mysql
            - ${PWD:-./}:/app
        entrypoint: "bash -c 'echo -e \"[client]\nuser=root\npassword=$$MYSQL_ROOT_PASSWORD\" > /root/.my.cnf && exec docker-entrypoint.sh mysqld'"
        environment:
            - MYSQL_ROOT_PASSWORD=supersecret
            - MYSQL_DATABASE=pelindev
            - MYSQL_USER=pelindev
            - MYSQL_PASSWORD=pelindev0
      
